apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.database.service.name }}
  labels: {{ .Values.database.service.selectorLabels | nindent 4 }}
spec:
  selector: {{ .Values.database.service.selectorLabels | nindent 4 }}
  ports:
  - protocol: TCP
    port: {{ .Values.database.service.port }}
    targetPort: 3306